apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operator-index
  namespace: openshift-marketplace
spec:
  image: {{ $.Values.mgmt.registry.url }}/cache-registryredhatio/redhat/redhat-operator-index:v4.10
  publisher: Red Hat
  sourceType: grpc
  displayName: TMETSE OperatorHub Quay Cache Proxy
  updateStrategy:
    registryPoll: 
      interval: 30m